version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html

volumes:
  wordpress_data:
